# Generated by Django 6.0.6 on 2026-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='is_synced',
            field=models.BooleanField(default=True),
        ),
    ]
